In [ ]:
import pandas as pd

In [ ]:
d=pd.read_csv('/content/bank.csv',delimiter=";")

In [ ]:
d

age          job   marital            education  default housing loan  \
0       56    housemaid   married             basic.4y       no      no   no   
1       57     services   married          high.school  unknown      no   no   
2       37     services   married          high.school       no     yes   no   
3       40       admin.   married             basic.6y       no      no   no   
4       56     services   married          high.school       no      no  yes   
...    ...          ...       ...                  ...      ...     ...  ...   
14765   49  blue-collar  divorced              unknown  unknown      no   no   
14766   49  blue-collar  divorced              unknown  unknown     yes   no   
14767   34   technician  divorced  professional.course       no      no   no   
14768   27     services   married          high.school       no      no   no   
14769   32  blue-collar    single             basic.6y       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
14765   cellular   jul         wed  ...         1    999         0   
14766   cellular   jul         wed  ...         1    999         0   
14767   cellular   jul         wed  ...         1    999         0   
14768   cellular   jul         wed  ...         4    999         0   
14769   cellular   jul         wed  ...         1    999         0   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
14765  nonexistent          1.4          93.918          -42.7      4.957   
14766  nonexistent          1.4          93.918          -42.7      4.957   
14767  nonexistent          1.4          93.918          -42.7      4.957   
14768  nonexistent          1.4          93.918          -42.7      4.957   
14769  nonexistent          1.4          93.000            NaN        NaN   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
14765       5228.1   no  
14766       5228.1   no  
14767       5228.1   no  
14768       5228.1   no  
14769          NaN  NaN  

[14770 rows x 21 columns]

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14770 entries, 0 to 14769
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             14770 non-null  int64  
 1   job             14770 non-null  object 
 2   marital         14770 non-null  object 
 3   education       14770 non-null  object 
 4   default         14770 non-null  object 
 5   housing         14770 non-null  object 
 6   loan            14770 non-null  object 
 7   contact         14770 non-null  object 
 8   month           14770 non-null  object 
 9   day_of_week     14770 non-null  object 
 10  duration        14770 non-null  int64  
 11  campaign        14770 non-null  int64  
 12  pdays           14770 non-null  int64  
 13  previous        14770 non-null  int64  
 14  poutcome        14770 non-null  object 
 15  emp.var.rate    14770 non-null  float64
 16  cons.price.idx  14770 non-null  float64
 17  cons.conf.idx   14769 non-null 

In [ ]:
d.shape

(14770, 21)

In [ ]:
d.describe()

age      duration      campaign    pdays  previous  \
count  14770.000000  14770.000000  14770.000000  14770.0   14770.0   
mean      39.809005    259.590183      2.769939    999.0       0.0   
std        9.071186    256.377464      3.150074      0.0       0.0   
min       20.000000      0.000000      1.000000    999.0       0.0   
25%       33.000000    107.000000      1.000000    999.0       0.0   
50%       39.000000    184.000000      2.000000    999.0       0.0   
75%       46.000000    321.000000      3.000000    999.0       0.0   
max       61.000000   3643.000000     56.000000    999.0       0.0   

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed  
count  14770.000000    14770.000000   14769.000000  14769.000000  14769.000000  
mean       1.242322       94.119872     -39.121999      4.898086   5208.599201  
std        0.149808        0.225726       2.881065      0.049866     18.526244  
min        1.100000       93.000000     -42.700000      4.855000   5191.000000  
25%        1.100000       93.994000     -41.800000      4.857000   5191.000000  
50%        1.100000       93.994000     -36.400000      4.864000   5191.000000  
75%        1.400000       94.465000     -36.400000      4.960000   5228.100000  
max        1.400000       94.465000     -36.400000      4.967000   5228.100000

In [ ]:
d.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     1
euribor3m         1
nr.employed       1
y                 1
dtype: int64

**Q1. What does the primary analysis of several categorical
features reveal?**


Administrative staff and technical specialists opened the deposit most of all. In relative terms, a high proportion of pensioners and students might be mentioned as well.       
Although in absolute terms married consumers more often agreed to the service, in relative terms the single was responded better.    
Best communication channel is secullar.        
The difference is evident between consumers who already use the services of banks and received a loan.       
Home ownership does not greatly affect marketing company performance.      


**Q2. Perform the following Exploratory Data Analysis tasks:**

a. Missing Value Analysis

In [ ]:
d.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     1
euribor3m         1
nr.employed       1
y                 0
dtype: int64

In [ ]:
d.dropna()

age          job   marital            education  default housing loan  \
0       56    housemaid   married             basic.4y       no      no   no   
1       57     services   married          high.school  unknown      no   no   
2       37     services   married          high.school       no     yes   no   
3       40       admin.   married             basic.6y       no      no   no   
4       56     services   married          high.school       no      no  yes   
...    ...          ...       ...                  ...      ...     ...  ...   
14764   28  blue-collar    single             basic.6y  unknown     yes   no   
14765   49  blue-collar  divorced              unknown  unknown      no   no   
14766   49  blue-collar  divorced              unknown  unknown     yes   no   
14767   34   technician  divorced  professional.course       no      no   no   
14768   27     services   married          high.school       no      no   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
14764   cellular   jul         wed  ...         1    999         0   
14765   cellular   jul         wed  ...         1    999         0   
14766   cellular   jul         wed  ...         1    999         0   
14767   cellular   jul         wed  ...         1    999         0   
14768   cellular   jul         wed  ...         4    999         0   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
14764  nonexistent          1.4          93.918          -42.7      4.957   
14765  nonexistent          1.4          93.918          -42.7      4.957   
14766  nonexistent          1.4          93.918          -42.7      4.957   
14767  nonexistent          1.4          93.918          -42.7      4.957   
14768  nonexistent          1.4          93.918          -42.7      4.957   

       nr.employed   y  
0           5191.0  no  
1           5191.0  no  
2           5191.0  no  
3           5191.0  no  
4           5191.0  no  
...            ...  ..  
14764       5228.1  no  
14765       5228.1  no  
14766       5228.1  no  
14767       5228.1  no  
14768       5228.1  no  

[14769 rows x 21 columns]

b. Label Encoding wherever required

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for i in d:
    if d[i].dtype=='object':
        d[i]=le.fit_transform(d[i])


In [ ]:
d.corr().style.background_gradient(cmap='coolwarm')

/usr/local/lib/python3.7/dist-packages/pandas/io/formats/style.py:2813: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
/usr/local/lib/python3.7/dist-packages/pandas/io/formats/style.py:2814: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax


**Q3. Build the following Supervised Learning models:**


a. Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
h=LogisticRegression()

In [ ]:
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score

In [ ]:
x1=d.drop(['y'],axis=1).values
y1=d['y'].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
#assigning numeric value 
d['y'] = l.fit_transform(d['y'])
d

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed  y  
0           5191.0  0  
1           5191.0  0  
2           5191.0  0  
3           5191.0  0  
4           5191.0  0  
...            ... ..  
41183       4963.6  1  
41184       4963.6  0  
41185       4963.6  0  
41186       4963.6  1  
41187       4963.6  0  

[41188 rows x 21 columns]

In [ ]:
d1=pd.get_dummies(d)

In [ ]:
x=d1.drop(['y'],axis=1).values
y=d1['y'].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.20,random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
i=LogisticRegression()

In [ ]:
i.fit(xtrain,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
p=i.predict(xtest)
i.predict_proba(xtest)

array([[0.90550775, 0.09449225],
       [0.89333374, 0.10666626],
       [0.98822368, 0.01177632],
       ...,
       [0.49299012, 0.50700988],
       [0.97245999, 0.02754001],
       [0.85762135, 0.14237865]])

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
accuracy_score(ytest,p)

0.9162418062636563

In [ ]:
confusion_matrix(ytest,p)

array([[7128,  191],
       [ 499,  420]])

In [ ]:
s=classification_report(ytest,p)

In [ ]:
print(s)

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      7319
           1       0.69      0.46      0.55       919

    accuracy                           0.92      8238
   macro avg       0.81      0.72      0.75      8238
weighted avg       0.91      0.92      0.91      8238



c. Naïve Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score,auc
from sklearn.metrics import roc_curve

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=0)

In [ ]:
c=GaussianNB()
c.fit(x_train,y_train)

GaussianNB()

In [ ]:
p=c.predict(x_test)


In [ ]:
accuracy_score(y_test,p)

0.8692345039650429

In [ ]:
z=classification_report(y_test,p)
print(z)

              precision    recall  f1-score   support

           0       0.94      0.91      0.93      5505
           1       0.42      0.55      0.48       674

    accuracy                           0.87      6179
   macro avg       0.68      0.73      0.70      6179
weighted avg       0.89      0.87      0.88      6179



d. KNN


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
s=StandardScaler()

In [ ]:
e=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
e.fit(xtrain,ytrain)

KNeighborsClassifier()

In [ ]:
t=e.predict(xtest)

In [ ]:
e.predict_proba(xtest)

array([[0.6, 0.4],
       [1. , 0. ],
       [1. , 0. ],
       ...,
       [1. , 0. ],
       [1. , 0. ],
       [0.8, 0.2]])

In [ ]:
accuracy_score(ytest,t)

0.9085170437991648

In [ ]:
u=classification_report(ytest,t)
print(u)

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      9139
           1       0.62      0.50      0.55      1158

    accuracy                           0.91     10297
   macro avg       0.78      0.73      0.75     10297
weighted avg       0.90      0.91      0.90     10297



e. SVM


In [ ]:
from sklearn.svm import SVC

In [ ]:
k=SVC(probability=True)

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.20,random_state=0)

In [ ]:
k.fit(xtrain,ytrain)

SVC(probability=True)

In [ ]:
i=k.predict(xtest)

In [ ]:
k.predict_proba(xtest)

array([[0.90725581, 0.09274419],
       [0.91058487, 0.08941513],
       [0.91449288, 0.08550712],
       ...,
       [0.90582781, 0.09417219],
       [0.9131568 , 0.0868432 ],
       [0.9103613 , 0.0896387 ]])

In [ ]:
accuracy_score(ytest,i)

0.8980335032774945

In [ ]:
confusion_matrix(ytest,i)

array([[7204,  115],
       [ 725,  194]])

In [ ]:
o=classification_report(ytest,i)
print(o)

              precision    recall  f1-score   support

           0       0.91      0.98      0.94      7319
           1       0.63      0.21      0.32       919

    accuracy                           0.90      8238
   macro avg       0.77      0.60      0.63      8238
weighted avg       0.88      0.90      0.87      8238



## logistic regression is consider the best algorithm because it provides the highest accuracy